var data = {
    "productDetails" : [
        {
            "index": 0,
            "name": "ELAND BENCH",
            "src": "images/elandBenchAutumn01.jpg",
            "width": 71 + '\"',
            "height": 41.5 + '\"',
            "depth": 27 + '\"',
            "fabric": 2 + "yards (standard width, no repeat)",
            "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
            "woodSpecies": "walnut, flat cut white oak",
            "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 1,
            "name": "METRO BENCH",
            "src": "images/metroBenchAutumn08.jpg",
            "width": 71 + '\"',
            "height": 41.5 + '\"',
            "depth": 27 + '\"',
            "fabric": 2 + "yards (standard width, no repeat)",
            "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
            "woodSpecies": "walnut, flat cut white oak",
            "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 2,
            "name": "ANGELES CHAIR",
            "src": "images/losAngelesChairAutumn05jpg",
            "width": 71 + '\"',
            "height": 41.5 + '\"',
            "depth": 27 + '\"',
            "fabric": 2 + "yards (standard width, no repeat)",
            "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
            "woodSpecies": "walnut, flat cut white oak",
            "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 3,
            "name": "CHICAGO I CHAIR",
            "src": "images/chicagoIChairAutumn13.jpg",
            "width": 71 + '\"',
            "height": 41.5 + '\"',
            "depth": 27 + '\"',
            "fabric": 2 + "yards (standard width, no repeat)",
            "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
            "woodSpecies": "walnut, flat cut white oak",
            "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 4,
            "name": "FRATELLI CHAIRS and TABLE",
            "src": "images/fratelliChairsTableAutumn13.jpg",
            "width": 71 + '\"',
            "height": 41.5 + '\"',
            "depth": 27 + '\"',
            "fabric": 2 + "yards (standard width, no repeat)",
            "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
            "woodSpecies": "walnut, flat cut white oak",
            "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 5,
            "name": "LOUIS I CHAIR",
            "src": "images/louisIChairAutumn07.jpg",
            "width": 71 + '\"',
            "height": 41.5 + '\"',
            "depth": 27 + '\"',
            "fabric": 2 + "yards (standard width, no repeat)",
            "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
            "woodSpecies": "walnut, flat cut white oak",
            "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 6,
            "name": "LOUIS II CHAIR",
            "src": "images/louisIIChairAutumn04.jpg",
            "width": 71 + '\"',
            "height": 41.5 + '\"',
            "depth": 27 + '\"',
            "fabric": 2 + "yards (standard width, no repeat)",
            "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
            "woodSpecies": "walnut, flat cut white oak",
            "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 7,
            "name": "MADRID DINING CHAIR",
            "src": "images/madridChairAutumn10.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 8,
            "name": "MILO CHAIR",
            "src": "images/miloChairAutumn07.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 9,
            "name": "PALMS I CHAIR",
            "src": "images/palms1ChairAutumn18.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 10,
            "name": "PALMS II CHAIR",
            "src": "images/palms2ChairAutumn14.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 11,
            "name": "TRACI CHAIR",
            "src": "images/traciChairAutumn08.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 12,
            "name": "TUULLA CHAIR",
            "src": "images/tuullaChairAutumn07.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 13,
            "name": "AIDEN II TABLE",
            "src": "images/AidenIITable.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 14,
            "name": "DAVID CONSOLE",
            "src": "images/davidConsole.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 15,
            "name": "MANHATTAN WALL UNIT",
            "src": "images/manhattanWallUnit.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 16,
            "name": "NICHOLAS I TABLE",
            "src": "images/nicholasITable.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 17,
            "name": "SHEA II CONSOLE",
            "src": "images/sheaIIConsole.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 18,
            "name": "JAMES DESK",
            "src": "images/jamesDesk.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 19,
            "name": "BRENTON TABLE (Rectangular)",
            "src": "images/brentonTableSQ.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 20,
            "name": "BRENTON TABLE (Round)",
            "src": "images/brentonRound.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 21,
            "name": "SALON SIDE TABLE",
            "src": "images/salonSide.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 22,
            "name": "SIMONE SIDE TABLE",
            "src": "images/simoneTable.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 23,
            "name": "SOTTO COFFEE TABLE",
            "src": "images/sottoTable.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 24,
            "name": "STUDIO COFFEE TABLE",
            "src": "images/studioTable.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 25,
            "name": "TRE I TABLE",
            "src": "images/tre1Table.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 26,
            "name": "BRANDON LOUNGE",
            "src": "images/brandonLounge.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 27,
            "name": "CHICAGO I DOUBLE BACK DEEP LOUNGE",
            "src": "images/chicagoIDoubleBackDeepLounge.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 28,
            "name": "COPPIA LOUNGE and TABLE",
            "src": "images/coppiaLounge.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 29,
            "name": "ISOLA LOUNGE",
            "src": "images/isolaLounge.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 30,
            "name": "BRANDON SECTIONAL",
            "src": "images/brandonSectional.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 31,
            "name": "DOUGLAS SECTIONAL",
            "src": "images/douglasSectional.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 32,
            "name": "MITOSI SECTIONAL",
            "src": "images/mitosiSectionalProducts.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 33,
            "name": "NICHOLAS I SECTIONAL",
            "src": "images/nicholasISectional.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 34,
            "name": "NICHOLAS II SECTIONAL",
            "src": "images/nicholasIISectional.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 35,
            "name": "SALON SECTIONAL",
            "src": "images/salonSectional.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 36,
            "name": "SHEA I SECTIONAL",
            "src": "images/sheaISectional.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 37,
            "name": "TRE II SECTIONAL",
            "src": "images/treIISectional.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 38,
            "name": "BRANDON SOFA",
            "src": "images/brandonSofa.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 39,
            "name": "CHICAGO I SOFA",
            "src": "images/chicagoISofa.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 40,
            "name": "CHICAGO II SOFA",
            "src": "images/chicagoIISofa.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 41,
            "name": "COVE SOFA",
            "src": "images/coveSofa.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 42,
            "name": "PALMS LOVESEAT",
            "src": "images/palmsLoveseat.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 43,
            "name": "SALON SOFA",
            "src": "images/salonSofa.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 44,
            "name": "TRE I SOFA",
            "src": "images/treISofa.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 45,
            "name": "TRE II SOFA",
            "src": "images/treIISofa.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 46,
            "name": "TUULLA LOVESEAT",
            "src": "images/tuullaLoveseat.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 47,
            "name": "WILLIAM SOFA",
            "src": "images/williamSofa.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 48,
            "name": "DADE BED",
            "src": "images/dadeBedAutumn04.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 49,
            "name": "NYLA BED",
            "src": "images/nylaBedAutumn07.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 50,
            "name": "PALMS BED",
            "src": "images/palmsBedAutumn06.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 51,
            "name": "TRACI BED",
            "src": "images/tracyBedAutumn04.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        },
        {
            "index": 52,
            "name": "ZURICH BED",
            "src": "images/zurichBed01.jpg",
            "width": 71 + '\"',
                        "height": 41.5 + '\"',
                        "depth": 27 + '\"',
                        "fabric": 2 + "yards (standard width, no repeat)",
                        "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                        "woodSpecies": "walnut, flat cut white oak",
                        "woodFinish": "matte natural, matte espresso"
        }
    ]

}
