
    var data = {
        "productDetails" : [
            {
                "index": 0,
                "href": 'products.html',
                "name": "ELAND BENCH",
                "src": "images/elandBenchAutumn01.jpg",
                "width": 71 + '\"',
                "height": 14.5 + '\"',
                "depth": 27 + '\"',
                "fabric": 2 + "yards (standard width, no repeat)",
                "leather": 40 + "sq ft (no blemishes, holes or stretch marks)",
                "woodSpecies": "walnut, flat cut white oak",
                "woodFinish": "matte natural, matte espresso"
            },
            {
                "index": 1,
                "href": 'products.html',
                "name": "METRO BENCH",
                "src": "images/metroBenchAutumn08.jpg",
                "width": 64 + '\"',
                "height": 14.5 + '\"',
                "depth": 24 + '\"',
                "fabric": 3 + "yards (standard width, no repeat)",
                "leather": 60 + "sq ft (no blemishes, holes or stretch marks)",
                "woodSpecies": "walnut, flat cut white oak",
                "woodFinish": "matte natural, matte espresso"
            },
            {
                "index": 2,
                "href": 'products.html',
                "name": "ANGELES CHAIR",
                "src": "images/losAngelesChairAutumn05.jpg",
                "width": 34 + '\"',
                "height": 29 + '\"',
                "depth": 32 + '\"',
                "seatHeight": 16 + '\"',
                "armHeight": 22 + '\"',
                "fabric": 3.5 + "yards (standard width, no repeat)",
                "leather": "NOT AVAILABLE",
                "metalFinish": "satin chrome"
            },
            {
                "index": 3,
                "href": 'products.html',
                "name": "CHICAGO I CHAIR",
                "src": "images/chicagoIChairAutumn13.jpg",
                "width": '28", 31" or 35"',
                "height": 33 + '\"',
                "depth": 34 + '\"',
                "seatHeight": 17.5 + '\"',
                "armHeight": 23 + '\"',
                "backHeight": 27 + '\"',
                "fabric": 8 + "yards (standard width, no repeat)",
                "leather": "NOT AVAILABLE",
                "metalFinish": "satin chrome"
            },
            {
                "index": 4,
                "href": 'products.html',
                "name": "FRATELLI CHAIRS and TABLE",
                "src": "images/fratelliChairsTableAutumn13.jpg",
                "width": '98" (group), 49" (chair), 19" (table)',
                "height": '32" (group), 32" (chair), 19" (table)',
                "depth": '35.5" (group), 34" (chair), 35.5" (table)',
                "fabric": '14 yards (group), 7 yards (each chair unit), (standard width, no repeat)',
                "leather": '250 sq ft (group), 140 sq ft (each chair unit)',
                "woodSpecies": "walnut, rift cut white oak, macassar ebony (highest quality veneer), zebrawood (highest quality veneer)",
                "woodFinish": "matte natural, matte espresso"
            },
            {
                "index": 5,
                "href": 'products.html',
                "name": "LOUIS I CHAIR",
                "src": "images/louisIChairAutumn07.jpg",
                "width": 43 + '\"',
                "height": 37 + '\"',
                "depth": 36 + '\"',
                "fabric": '6.5 (standard width, no repeat)',
                "leather": '130 sq ft (no blemishes, holes or stretch marks)',
                "woodSpecies": "maple, walnut (legs)",
                "woodFinish": "matte natural, matte espresso (legs)",
                "metalFinish": "satin chrome, matte black, matte bronze (swivel x-base)",
                "styles": "chair available with legs or swivel, matching ottomans with legs or x-base",
                "message": "contact us for more information"
            },
            {
                "index": 6,
                "href": 'products.html',
                "name": "LOUIS II CHAIR",
                "src": "images/louisIIChairAutumn04.jpg",
                "width": 71 + '\"',
                "height": 41.5 + '\"',
                "depth": 27 + '\"',
                "seatHeight": 15.5 + '\"',
                "armHeight": 17 + '\"',
                "fabric": 6 + "yards (standard width, no repeat)",
                "leather": 120 + "sq ft (no blemishes, holes or stretch marks)",
                "woodSpecies": "maple, walnut legs",
                "woodFinish": "matte natural, matte espresso (legs)",
                "metalFinish": "satin chrome, matte black, matte bronze (swivel x-base)",
                "styles": "chair available with legs or swivel, matching ottomans with legs or x-base",
                "message": "contact us for more information"
            },
            {
                "index": 7,
                "href": 'products.html',
                "name": "MADRID DINING CHAIR",
                "src": "images/madridChairAutumn10.jpg",
                "width": 26 + '\"',
                "height": 31.5 + '\"',
                "depth": 24 + '\"',
                "seatHeight": 18 + '\"',
                "armHeight": 24 + '\"',
                "backHeight": 31.5 + '\"',
                "fabric": 1.5 + "yards (standard width, no repeat)",
                "leather": 30 + "sq ft (no blemishes, holes or stretch marks)",
                "woodSpecies": "walnut, flat cut white oak",
                "woodFinish": "matte natural, matte espresso (legs)",
                "styles": "available as arm chair, with no arms, as a bar stool",
                "message": "contact us for more information"
            },
            {
                "index": 8,
                "href": "products.html",
                "name": "MILO CHAIR",
                "src": "images/miloChairAutumn07.jpg",
                "width": 31 + '\"',
                "height": 34 + '\"',
                "depth": 35 + '\"',
                "seatHeight": 15 + '\"',
                "armHeight": 20 + '\"',
                "backHeight": 34 + '\"',
                "fabric": 5 + "yards (standard width, no repeat)",
                "leather": "NOT AVAILABLE",
                "woodSpecies": "maple, walnut",
                "woodFinish": "matte natural, matte espresso (legs)"
            },
            {
                "index": 9,
                "href": "products.html",
                "name": "PALMS I CHAIR",
                "src": "images/palms1ChairAutumn18.jpg",
                "width": 40 + '\"',
                "height": 34.5 + '\"',
                "depth": 35 + '\"',
                "seatHeight": 15.5 + '\"',
                "armHeight": 16 + '\"',
                "backHeight": 34.5 + '\"',
                "fabric": 6 + "yards (standard width, no repeat)",
                "leather": 120 + "sq ft (no blemishes, holes or stretch marks)",
                "woodSpecies": "maple, walnut (legs)",
                "woodFinish": "matte natural, matte espresso (legs)",
                "ottoman": "matching ottoman available",
                "message": "contact us for more information"
            },
            {
                "index": 10,
                "href": "products.html",
                "name": "PALMS II CHAIR",
                "src": "images/palms2ChairAutumn14.jpg",
                "width": 35 + '\"',
                "height": 32 + '\"',
                "depth": 34 + '\"',
                "seatHeight": 15.5 + '\"',
                "armHeight": 16 + '\"',
                "backHeight": 32 + '\"',
                "fabric": 5.5 + "yards (standard width, no repeat)",
                "leather": 110 + "sq ft (no blemishes, holes or stretch marks)",
                "woodSpecies": "maple, walnut (legs)",
                "woodFinish": "matte natural, matte espresso (legs)",
                "metalFinish": "satin chrome, matte black, matte bronze (swivel x-base)",
                "styles": "available with legs or swivel x-base",
                "ottoman": "matching ottoman available with legs or swivel x-base",
                "message": "contact us for more information"
            },
            {
                "index": 11,
                "href": "products.html",
                "name": "TRACI CHAIR",
                "src": "images/traciChairAutumn08.jpg",
                "width": 30 + '\"',
                "height": 28 + '\"',
                "depth": 36 + '\"',
                "seatHeight": 15.5 + '\"',
                "backHeight": 28 + '\"',
                "fabric": 2.5 + "yards (standard width, no repeat)",
                "leather": 50 + "sq ft (no blemishes, holes or stretch marks)",
                "woodSpecies": "walnut, flat cut white oak",
                "woodFinish": "matte natural, matte espresso"
            },
            {
                "index": 12,
                "href": "products.html",
                "name": "TUULLA CHAIR",
                "src": "images/tuullaChairAutumn07.jpg",
                "width": 39 + '\"',
                "height": 38 + '\"',
                "depth": 35 + '\"',
                "fabric": 7 + "yards (standard width, no repeat)",
                "leather": "NOT AVAILABLE",
                "metalFinish": "satin chrome, matte black, matte bronze (swivel x-base)"
            },
            {
                "index": 13,
                "href": "products.html",
                "name": "AIDEN II CONSOLE",
                "src": "images/AidenIITable.jpg",
                "width": 84 + '\"',
                "height": 28 + '\"',
                "depth": 16 + '\"',
                "woodSpecies": "flat cut walnut, quarter cut walnut, rift cut walnut",
                "woodFinish": "matte natural, matte espresso",
                "metalFinish": "satin chrome, matte black, matte bronze"
            },
            {
                "index": 14,
                "href": "products.html",
                "name": "DAVID CONSOLE",
                "src": "images/davidConsole.jpg",
                "width": 71 + '\"',
                "height": 12.5 + '\"',
                "depth": 25 + '\"',
                "woodSpecies": "flat cut walnut, quarter cut walnut, rift cut walnut, macassar ebony (highest quality veneer), zebrawood (highest quality veneer)",
                "woodFinish": "matte natural, matte espresso",
                "metalFinish": "satin chrome, matte black, matte bronze"
            },
            {
                "index": 15,
                "href": "products.html",
                "name": "MANHATTAN WALL UNIT",
                "src": "images/manhattanWallUnit.jpg",
                "width": 76 + '\"',
                "height": 8.75 + '\"',
                "depth": 15 + '\"',
                "woodSpecies": "walnut, flat cut walnut, rift cut white oak",
                "woodFinish": "matte natural, matte espresso",
                "metalFinish": "satin chrome"
            },
            {
                "index": 16,
                "href": "products.html",
                "name": "NICHOLAS I TABLE",
                "src": "images/nicholasITable.jpg",
                "width": 39 + '\"',
                "height": 23 + '\"',
                "depth": 18 + '\"',
                "woodSpecies": "walnut, rift cut white oak",
                "woodFinish": "matte natural, matte espresso",
                "metalFinish": "satin chrome"
            },
            {
                "index": 17,
                "href": "products.html",
                "name": "SHEA II CONSOLE",
                "src": "images/sheaIIConsole.jpg",
                "width": 71 + '\"',
                "height": 12.5 + '\"',
                "depth": 25 + '\"',
                "woodSpecies": "flat cut walnut, quarter cut walnut, rift cut white oak",
                "woodFinish": "matte natural, matte espresso",
                "metalFinish": "satin chrome, matte black, matte bronze"
            },
            {
                "index": 18,
                "href": "products.html",
                "name": "JAMES DESK",
                "src": "images/jamesDesk.jpg",
                "width": '63" to 87" (adjustable)',
                "height": 28 + '\"',
                "depth": 23.5 + '\"',
                "woodFinish": "veneer, sophisticated in design and quality"
            },
            {
                "index": 19,
                "href": "products.html",
                "name": "BRENTON TABLE (Rectangular)",
                "src": "images/brentonTableSQ.jpg",
                "width": 52 + '\"',
                "height": 14 + '\"',
                "depth": 35 + '\"',
                "woodSpecies": "walnut, rift cut white oak",
                "woodFinish": "matte natural, matte espresso"
            },
            {
                "index": 20,
                "href": "products.html",
                "name": "BRENTON TABLE (Round)",
                "src": "images/brentonRound.jpg",
                "diameter": '24", 30", 36", 40" or 46"',
                "height": 15 + '\"',
                "woodSpecies": "walnut, rift cut white oak",
                "woodFinish": "matte natural, matte espresso"
            },
            {
                "index": 21,
                "href": "products.html",
                "name": "SALON SIDE TABLE",
                "src": "images/salonSide.jpg",
                "width": 13.5 + '\"',
                "height": 22.5 + '\"',
                "depth": 13.5 + '\"',
                "woodSpecies": "walnut, rift cut white oak",
                "woodFinish": "matte natural, matte espresso"
            },
            {
                "index": 22,
                "href": "products.html",
                "name": "SIMONE SIDE TABLE",
                "src": "images/simoneTable.jpg",
                "width": 26 + '\"',
                "height": 18 + '\"',
                "depth": 22 + '\"',
                "woodSpecies": "flat cut walnut, quarter cut walnut, rift cut white oak, zebrawood (highest quality veneer for waterfall effect)",
                "woodFinish": "matte natural, matte espresso",
                "metalFinish": "satin chrome"
            },
            {
                "index": 23,
                "href": "products.html",
                "name": "SOTTO COFFEE TABLE",
                "src": "images/sottoTable.jpg",
                "width": '32" (upper table), 32" (lower table)',
                "height": '11.5" (upper table), 9.5" (lower table)',
                "depth": '36" (upper table), 32" (lower table)',
                "woodSpecies": "walnut (solid), rift cut white oak (solid), macassar ebony (highest quality veneer for waterfall effect), zebrawood (highest quality veneer for waterfall effect)",
                "woodFinish": "matte natural, matte espresso"
            },
            {
                "index": 24,
                "href": "products.html",
                "name": "STUDIO COFFEE TABLE",
                "src": "images/studioTable.jpg",
                "width": 56 + '\"',
                "height": 12.5 + '\"',
                "depth": 36 + '\"',
                "woodSpecies": "walnut, rift cut white oak",
                "woodFinish": "matte natural, matte espresso",
                "metalFinish": "satin chrome"
            },
            {
                "index": 25,
                "href": "products.html",
                "name": "TRE I TABLE",
                "src": "images/tre1Table.jpg",
                "width": 18 + '\"',
                "height": 21 + '\"',
                "depth": 15 + '\"',
                "woodSpecies": "walnut, rift cut white oak",
                "woodFinish": "matte natural, matte espresso",
                "metalFinish": "satin chrome"
            },
            {
                "index": 26,
                "href": "products.html",
                "name": "BRANDON LOUNGE",
                "src": "images/brandonLounge.jpg",
                "width": '63" to 87" (adjustable)',
                "height": 28 + '\"',
                "depth": 23.5 + '\"'
            },
            {
                "index": 27,
                "href": "products.html",
                "name": "CHICAGO I DOUBLE BACK DEEP LOUNGE",
                "src": "images/chicagoIDoubleBackDeepLounge.jpg",
                "width": '70" or 78"',
                "height": 33 + '\"',
                "depth": '34" or 52"',
                "seatHeight": 17.5 + '\"',
                "armHeight": 24 + '\"',
                "backHeight": 27 + '\"',
                "fabric": '13.5 yards (70"), 16 yards (78") (standard width, no repeat)',
                "leather": 'NOT AVAILABLE',
                "metalFinish": "satin chrome"
            },
            {
                "index": 28,
                "href": "products.html",
                "name": "COPPIA LOUNGE and TABLE",
                "src": "images/coppiaLounge.jpg",
                "width": '82" (group) 45" (table)',
                "height": '47" (group) 21" (table)',
                "depth": '32" (lounge) 15" (table)',
                "seatHeight": 16.5 + '\"',
                "armHeight": 27 + '\"',
                "backHeight": 21 + '\"',
                "fabric": 13.5 + "yards (standard width, no repeat)",
                "leather": 260 + "sq ft (no blemishes, holes or stretch marks)",
                "woodSpecies": "walnut, rift cut white oak",
                "woodFinish": "matte natural, matte espresso",
                "metalFinish": "satin chrome"
            },
            {
                "index": 29,
                "href": "products.html",
                "name": "ISOLA LOUNGE",
                "src": "images/isolaLounge.jpg",
                "width": 64 + '\"',
                "height": 32 + '\"',
                "depth": 64 + '\"',
                "seatHeight": 16 + '\"',
                "armHeight": 23 + '\"',
                "backHeight": 23 + '\"',
                "fabric": 14 + "yards (standard width, no repeat)",
                "leather": 280 + "sq ft (no blemishes, holes or stretch marks)",
                "woodSpecies": "maple, walnut (base and legs)",
                "woodFinish": "matte natural, matte espresso"
            },
            {
                "index": 30,
                "href": "products.html",
                "name": "BRANDON SECTIONAL",
                "src": "images/brandonSectional.jpg",
                "width": '99" (group) 67" (sofa) 32" (lounge)',
                "height": 34 + '\"',
                "depth": '62" (group) 36" (sofa) 62" (lounge)',
                "seatHeight": 16 + '\"',
                "armHeight": 23 + '\"',
                "fabric": '15 yards (group) 8 yards (sofa) 7 yards (lounge) (standard width, no repeat)',
                "leather": "NOT AVAILABLE",
                "woodSpecies": "maple, walnut (legs)",
                "woodFinish": "matte natural, matte espresso (legs)"
            },
            {
                "index": 31,
                "href": "products.html",
                "name": "DOUGLAS SECTIONAL",
                "src": "images/douglasSectional.jpg",
                "width": '183" (group) 77" (sofa) 51" (center) 55" (lounge)',
                "height": '33" (sofa) 33" (center) 35" (lounge)',
                "depth": '73" (group) 39" (sofa) 37" (center) 61" (lounge)',
                "seatHeight": 15.5 + '\"',
                "armHeight": 26 + '\"',
                "backHeight": 26 + '\"',
                "fabric": '29 yards (group) 11 yards (sofa) 7 yards (center) 11 yards (lounge) (standard width, no repeat)',
                "leather": 'NOT AVAILABLE',
                "woodSpecies": "maple (legs)",
                "woodFinish": "matte espresso (legs)",
                "message": "more configurations available (see tear sheet)",
                "style": "The Douglas is a tight seat sectional with 3 unique pieces and configurable/modular"
            },
            {
                "index": 32,
                "href": "products.html",
                "name": "MITOSI SECTIONAL",
                "src": "images/mitosiSectionalProducts.jpg",
                "width": '122" (2 pc. group) 72" (individual)',
                "height": 33 + '\"',
                "depth": '69" (group) 39" (individual)',
                "seatHeight": 25 + '\"',
                "armHeight": 25 + '\"',
                "backHeight": 33 + '\"',
                "fabric": '18 yards (2pc. group) 11 yards (individual) (standard width, no repeat)',
                "leather": 'NOT AVAILABLE',
                "message": "more configurations available (see tear sheet)",
                "style": "The Mitosi is a tight seat sectional. When 5 units are fit together it closes to make a pentagon"
            },
            {
                "index": 33,
                "href": "products.html",
                "name": "NICHOLAS I SECTIONAL",
                "src": "images/nicholasISectional.jpg",
                "width": '129" (group) 75" (sofa) 54" (lounge) 18" (table)',
                "height": '34" (group) 34" (sofa) 34" (lounge) 23" (table)',
                "depth": '78" (group) 39" (sofa) 78" (lounge) 39" (table)',
                "seatHeight": 15.5 + '\"',
                "armHeight": 24 + '\"',
                "fabric": '22 yards (group) 10 yards (sofa) 12 yards (lounge) (standard width, no repeat)',
                "leather": 'NOT AVAILABLE',
                "woodSpecies": "walnut, rift cut white oak (table)",
                "woodFinish": "matte natural, matte espresso (legs)",
                "metalFinish": "satin chrome (sofa and lounge legs, table base)",
                "message": "more configurations available (see tear sheet)",
                "style": "The Nicholas I Sectional is a tight seat, has a tight cushion. Available with or without an inset console table."
            },
            {
                "index": 34,
                "href": "products.html",
                "name": "NICHOLAS II SECTIONAL",
                "src": "images/nicholasIISectional.jpg",
                "width": '114" (group) 66" (sofa) 48" (lounge)',
                "height": 34 + '\"',
                "depth": '56" (group) 39" (sofa) 56" (lounge) loose seat',
                "seatHeight": 15.5 + '\"',
                "armHeight": 24 + '\"',
                "backHeight": 34 + '\"',
                "fabric": '22 yards (group) 11 yards (each unit) (standard width, no repeat)',
                "leather": '44 sq ft (group) 220 sq ft (each unit) (no blemishes, holes or stretch marks)',
                "metalFinish": "satin chrome (legs)",
                "message": "more configurations available (see tear sheet)",
                "style": "The Nicholas II Sectional has a cushion seat. Available with or without an inset console table."
            },
            {
                "index": 35,
                "href": "products.html",
                "name": "SALON SECTIONAL",
                "src": "images/salonSectional.jpg",
                "width": '103" (group) 64" (sofa) 40" (lounge) 13.5" (table)',
                "height": '33" (sofa) 33" (lounge) 22.5" (table)',
                "depth": '69" (group) 40" (sofa) 69" (lounge)',
                "fabric": '21 yards (group) 10 yards (sofa) 11 yards (lounge) (standard width, no repeat)',
                "leather": '420 sq ft (group) 200 sq ft (sofa) 220 sq ft (lounge) (no blemishes, holes or stretch marks)',
            },
            {
                "index": 36,
                "href": "products.html",
                "name": "SHEA I SECTIONAL",
                "src": "images/sheaISectional.jpg",
                "width": '114" (group) 114" (sofa) 39" (loveseat) 71" (table)',
                "height": '36" (sofa) 36" (loveseat) 25" (table)',
                "depth": '105" (group) 47" (sofa) 39" (loveseat) 12.5" (table)',
                "seatHeight": 16 + '\"',
                "armHeight": 21.5 + '\"',
                "backHeight": 26 + '\"',
                "fabric": '27 yards (group) 17 yards (sofa) 10 yards (loveseat) (standard width, no repeat)',
                "leather": '540 sq ft (group) 340 sq ft (sofa) 180 sq ft (lounge) (no blemishes, holes or stretch marks)',
                "woodSpecies": 'flat cut walnut, quarter cut walnut, rift cut white oak (highest quality veneer for a seem-less waterfall look)',
                "metalFinish": "satin chrome (sofa and loveseat), satin chrome, matte black, matte bronze (console)"
            },
            {
                "index": 37,
                "href": "products.html",
                "name": "TRE II SECTIONAL",
                "src": "images/treIISectional.jpg",
                "width": '89" (group) 54" (sofa) 35" (lounge)',
                "height": 33 + '\"',
                "depth": '54" (group) 35" (sofa) 54" (lounge)',
                "seatHeight": 16.5 + '\"',
                "armHeight": 21.5 + '\"',
                "backHeight": 26.5 + '\"',
                "fabric": '16 yards (group) 8 yards (each unit) (standard width, no repeat)',
                "leather": '320 sq ft (group) 160 sq ft (each unit) (no blemishes, holes or stretch marks)',
                "metalFinish": "satin chrome"
            },
            {
                "index": 38,
                "href": "products.html",
                "name": "BRANDON SOFA",
                "src": "images/brandonSofa.jpg",
                "width": '63" to 87" (adjustable)',
                "height": 28 + '\"',
                "depth": 23.5 + '\"',
            },
            {
                "index": 39,
                "href": "products.html",
                "name": "CHICAGO I SOFA",
                "src": "images/chicagoISofa.jpg",
                "width": '87", 96", 107"',
                "height": 33 + '\"',
                "depth": 34 + '\"',
                "seatHeight": 17.5 + '\"',
                "armHeight": 24 + '\"',
                "backHeight": 27 + '\"',
                "fabric": '15.5 yards, 16 yards, 17.5 yards (standard width, no repeat)',
                "leather": 'NOT AVAILABLE',
                "metalFinish": "satin chrome (base)"
            },
            {
                "index": 40,
                "href": "products.html",
                "name": "CHICAGO II SOFA",
                "src": "images/chicagoIISofa.jpg",
                "width": 96 + '\"',
                "height": 33 + '\"',
                "depth": 36 + '\"',
                "seatHeight": 16.5 + '\"',
                "armHeight": 23 + '\"',
                "backHeight": 27 + '\"',
                "fabric": 16 + "yards (standard width, no repeat)",
                "leather": "NOT AVAILABLE",
                "metalFinish": "satin chrome (base)"
            },
            {
                "index": 41,
                "href": "products.html",
                "name": "COVE SOFA",
                "src": "images/coveSofa.jpg",
                "width": 92 + '\"',
                "height": 33 + '\"',
                "depth": 56 + '\"',
                "seatHeight": 16 + '\"',
                "armHeight": 22.5 + '\"',
                "backHeight": 27 + '\"',
                "fabric": 11 + "yards (standard width, no repeat)",
                "leather": "NOT AVAILABLE",
                "metalFinish": "satin chrome"
            },
            {
                "index": 42,
                "href": "products.html",
                "name": "PALMS LOVESEAT",
                "src": "images/palmsLoveseat.jpg",
                "width": 60 + '\"',
                "height": 31 + '\"',
                "depth": 34 + '\"',
                "seatHeight": 15.5 + '\"',
                "armHeight": 16 + '\"',
                "backHeight": 31 + '\"',
                "fabric": 10 + "yards (standard width, no repeat)",
                "leather": "260 sq ft (no blemishes, holes or stretch marks)",
                "woodSpecies": "maple, walnut (legs)",
                "woodFinish": "matte natural, matte espresso"
            },
            {
                "index": 43,
                "href": "products.html",
                "name": "SALON SOFA",
                "src": "images/salonSofa.jpg",
                "width": '84" or 98"',
                "height": 33 + '\"',
                "depth": 40 + '\"',
                "seatHeight": 16.5 + '\"',
                "armHeight": 21.5 + '\"',
                "backHeight": 27 + '\"',
                "fabric": '15 yards (84" sofa) 16 yards (98" sofa) (standard width, no repeat)',
                "leather": '300 sq ft (84" sofa) 320 sq ft (98" sofa) (no blemishes, holes or stretch marks)'
            },
            {
                "index": 44,
                "href": "products.html",
                "name": "TRE I SOFA",
                "src": "images/treISofa.jpg",
                "width": '105" or 118"',
                "height": 33 + '\"',
                "depth": 36 + '\"',
                "seatHeight": 16.5 + '\"',
                "armHeight": '21.5" (one side) 19" (opposite side)',
                "backHeight": 26.5 + '\"',
                "fabric": '14.5 yards (105" sofa) 17.5 yards (118" sofa) (standard width, no repeat)',
                "leather": '290 sq ft (105" sofa) 344 sq ft (118" sofa) (no blemishes, holes or stretch marks)',
                "metalFinish": "satin chrome"
            },
            {
                "index": 45,
                "href": "products.html",
                "name": "TRE II SOFA",
                "src": "images/treIISofa.jpg",
                "width": 89 + '\"',
                "height": 21.5 + '\"',
                "depth": 35 + '\"',
                "seatHeight": 16.5 + '\"',
                "armHeight": 21 + '\"',
                "backHeight": 26.5 + '\"',
                "fabric": '11.5 yards (standard width, no repeat)',
                "leather": '230 sq ft (no blemishes, holes or stretch marks)',
                "metalFinish": "satin chrome"
            },
            {
                "index": 46,
                "href": "products.html",
                "name": "TUULLA LOVESEAT",
                "src": "images/tuullaLoveseat.jpg",
                "width": 59 + '\"',
                "height": 38 + '\"',
                "depth": 35 + '\"',
                "seatHeight": 15.5 + '\"',
                "armHeight": 22 + '\"',
                "fabric": "10 yards (standard width, no repeat)",
                "leather": "NOT AVAILABLE",
                "metalFinish": "satin chrome, matte black, matte bronze (base)"
            },
            {
                "index": 47,
                "href": "products.html",
                "name": "WILLIAM SOFA",
                "src": "images/williamSofa.jpg",
                "width": '85", 98" or 118"',
                "height": 32 + '\"',
                "depth": 36 + '\"',
                "seatHeight": 16 + '\"',
                "armHeight": 18.5 + '\"',
                "backHeight": 13 + '\"',
                "fabric": '12 yards (85" sofa) 14 yards (98" sofa), 16 yards (118" sofa) (standard width, no repeat)',
                "leather": '240 sq ft (85" sofa) 280 sq ft (98" sofa) 320 sq ft (118" sofa) (no blemishes, holes or stretch marks)',
                "metalFinish": "satin chrome, matte black, matte bronze"
            }

        ]

    }



